# Generated by Django 2.2.2 on 2019-06-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_degree',
            fields=[
                ('ID_academic_degree', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'academic_degree',
            },
        ),
        migrations.CreateModel(
            name='Academic_title',
            fields=[
                ('ID_academic_title', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'academic_title',
            },
        ),
        migrations.CreateModel(
            name='Bibliographic_database',
            fields=[
                ('ID_bibliographic_database', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bibliographic_database',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ID_city', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Confirmed', models.BooleanField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID_department', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID_employee', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('FIO', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('ID_academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Academic_degree')),
                ('ID_academic_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Academic_title')),
                ('ID_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('ID_faculty', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('ID_magazine', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Confirmed', models.BooleanField()),
            ],
            options={
                'db_table': 'magazine',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('ID_position', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('ID_publication', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Note', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
                ('Initial_page', models.CharField(max_length=255)),
                ('Page_final', models.CharField(max_length=255)),
                ('Tom', models.CharField(max_length=255)),
                ('Issue_number', models.CharField(max_length=255)),
                ('DOI', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=255)),
                ('ID_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.City')),
                ('ID_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Employee')),
                ('ID_magazine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Magazine')),
            ],
            options={
                'db_table': 'publication',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('ID_status', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Type_publication',
            fields=[
                ('ID_type_publication', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_publication',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('ID_year', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'year',
            },
        ),
        migrations.CreateModel(
            name='PublicationEmployee',
            fields=[
                ('ID_publication_employee', models.AutoField(primary_key=True, serialize=False)),
                ('ID_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Employee')),
                ('ID_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Publication')),
            ],
            options={
                'db_table': 'publication_employee',
            },
        ),
        migrations.CreateModel(
            name='PublicationBibliographic_database',
            fields=[
                ('ID_publication_bibliographic', models.AutoField(primary_key=True, serialize=False)),
                ('ID_bibliographic_database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Bibliographic_database')),
                ('ID_publication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Publication')),
            ],
            options={
                'db_table': 'publication_bibliographic',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='ID_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Status'),
        ),
        migrations.AddField(
            model_name='publication',
            name='ID_type_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Type_publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='ID_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ID_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Position'),
        ),
        migrations.AddField(
            model_name='department',
            name='ID_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Faculty'),
        ),
    ]
