# Generated by Django 2.2.2 on 2019-06-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='File',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
