# Generated by Django 2.2.2 on 2019-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('ID_publisher', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Confirmed', models.BooleanField()),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
    ]
