# Generated by Django 2.2.2 on 2019-06-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_publication_id_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='ID_publisher',
        ),
    ]
