# Generated by Django 2.2.2 on 2019-06-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ID_benefit_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Benefit_type'),
            preserve_default=False,
        ),
    ]
