# Generated by Django 2.2.2 on 2019-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_publication_id_benefit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulture',
            fields=[
                ('ID_vulture', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vulture',
            },
        ),
    ]
