# Generated by Django 2.2.2 on 2019-06-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_publication_id_vulture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_article',
            fields=[
                ('ID_type_article', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'type_article',
            },
        ),
    ]
