# Generated by Django 2.2.2 on 2019-06-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_publication_id_type_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_finance',
            fields=[
                ('ID_source_finance', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'source_finance',
            },
        ),
    ]
