# Generated by Django 2.2.2 on 2019-06-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0013_source_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ID_source_finance',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Source_finance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='State_registration_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
