# Generated by Django 2.2.2 on 2019-06-17 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0014_auto_20190615_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('ID_user_profile', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=255)),
                ('ID_academic_degree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Academic_degree')),
                ('ID_academic_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Academic_title')),
                ('ID_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Department')),
                ('ID_position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='publication.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
