# Generated by Django 2.2.2 on 2019-06-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0015_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='ID_employee',
        ),
        migrations.AddField(
            model_name='publication',
            name='ID_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='publication.UserProfile'),
            preserve_default=False,
        ),
    ]
